[package]
name = "pop-primitives"
license = "GPL-3.0-only"
version = "0.0.0"
edition = "2021"

[dependencies]
bounded-collections = { version = "0.1", default-features = false }

scale = { package = "parity-scale-codec", version = "3.6.9", default-features = false, features = ["derive"] }
scale-decode = { version = "0.10.0", default-features = false, features = ["derive"], optional = true }
scale-encode = { version = "0.5.0", default-features = false, features = ["derive"], optional = true }
scale-info = { version = "2.6", default-features = false, features = ["derive"], optional = true }

#scale = { workspace = true, features = ["max-encoded-len"] }
#scale-decode = { workspace = true, features = ["derive"], optional = true }
#scale-encode = { workspace = true, features = ["derive"], optional = true }
#scale-info = { workspace = true, features = ["derive"], optional = true }

[features]
default = ["std"]
std = [
    "bounded-collections/std",
    "scale/std",
    "scale-decode/std",
    "scale-encode/std",
    "scale-info/std",
]
devnet = []
testnet = []