[package]
name = "pop-primitives"
license = "GPL-3.0-only"
version = "0.0.0"
edition = "2021"

[dependencies]
bounded-collections = { version = "0.1", default-features = false }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-decode = { version = "0.10.0", default-features = false, features = ["derive"], optional = true }
scale-encode = { version = "0.5.0", default-features = false, features = ["derive"], optional = true }
scale-info = { version = "2.10", default-features = false, features = ["derive"], optional = true }
sp-std = { version = "14.0.0", default-features = false }

[features]
default = ["std"]
std = [
    "bounded-collections/std",
    "scale/std",
    "scale-decode/std",
    "scale-encode/std",
    "scale-info/std",
    "sp-std/std",
]
devnet = []
testnet = []
assets = []
cross-chain = []
nfts = []
