[workspace.package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
repository = "https://github.com/paritytech/polkadot-sdk.git"
license = "GPL-3.0-only"

[workspace]
exclude = [ "integration-tests" ]
members = [
	"node",
	"runtime",
]
resolver = "2"

[profile.release]
# Polkadot runtime requires unwinding.
panic = "unwind"
opt-level = 3

# make sure dev builds with backtrace do not slow us down
[profile.dev.package.backtrace]
inherits = "release"

[profile.production]
inherits = "release"
lto = true
codegen-units = 1

[profile.testnet]
inherits = "release"
debug = 1               # debug symbols are useful for profilers
debug-assertions = true
overflow-checks = true

# The list of dependencies below (which can be both direct and indirect dependencies) are crates
# that are suspected to be CPU-intensive, and that are unlikely to require debugging (as some of
# their debug info might be missing) or to require to be frequently recompiled. We compile these
# dependencies with `opt-level=3` even in "dev" mode in order to make "dev" mode more usable.
# The majority of these crates are cryptographic libraries.
#
# If you see an error mentioning "profile package spec ... did not match any packages", it
# probably concerns this list.
#
# This list is ordered alphabetically.
[profile.dev.package]
blake2 = { opt-level = 3 }
blake2b_simd = { opt-level = 3 }
chacha20poly1305 = { opt-level = 3 }
cranelift-codegen = { opt-level = 3 }
cranelift-wasm = { opt-level = 3 }
crc32fast = { opt-level = 3 }
crossbeam-deque = { opt-level = 3 }
crypto-mac = { opt-level = 3 }
curve25519-dalek = { opt-level = 3 }
ed25519-dalek = { opt-level = 3 }
flate2 = { opt-level = 3 }
futures-channel = { opt-level = 3 }
hash-db = { opt-level = 3 }
hashbrown = { opt-level = 3 }
hmac = { opt-level = 3 }
httparse = { opt-level = 3 }
integer-sqrt = { opt-level = 3 }
keccak = { opt-level = 3 }
libm = { opt-level = 3 }
librocksdb-sys = { opt-level = 3 }
libsecp256k1 = { opt-level = 3 }
libz-sys = { opt-level = 3 }
mio = { opt-level = 3 }
nalgebra = { opt-level = 3 }
num-bigint = { opt-level = 3 }
parking_lot = { opt-level = 3 }
parking_lot_core = { opt-level = 3 }
percent-encoding = { opt-level = 3 }
primitive-types = { opt-level = 3 }
reed-solomon-novelpoly = { opt-level = 3 }
ring = { opt-level = 3 }
rustls = { opt-level = 3 }
sha2 = { opt-level = 3 }
sha3 = { opt-level = 3 }
smallvec = { opt-level = 3 }
snow = { opt-level = 3 }
substrate-bip39 = { opt-level = 3 }
twox-hash = { opt-level = 3 }
uint = { opt-level = 3 }
wasmi = { opt-level = 3 }
x25519-dalek = { opt-level = 3 }
yamux = { opt-level = 3 }
zeroize = { opt-level = 3 }

[workspace.dependencies]
clap = { version = "4.4.10", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
color-print = "0.3.4"
futures = "0.3.28"
hex-literal = { version = "0.4.1" }
jsonrpsee = { version = "0.16.2", features = ["server"] }
log = { version = "0.4.20", default-features = false }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
smallvec = "1.11.0"

# Substrate
frame-benchmarking = { default-features = false, version = "25.0.0" }
frame-benchmarking-cli = { version = "29.0.0" }
frame-executive = { default-features = false , version = "25.0.0" }
frame-support = { default-features = false , version = "25.0.0" }
frame-system = { default-features = false , version = "25.0.0" }
frame-system-benchmarking = { default-features = false, version = "25.0.0" }
frame-system-rpc-runtime-api = { default-features = false , version = "23.0.0" }
frame-try-runtime = { default-features = false, version = "0.31.0" }
pallet-aura = { default-features = false, version = "24.0.0" }
pallet-authorship = { default-features = false , version = "25.0.0" }
pallet-balances = { default-features = false , version = "25.0.0" }
pallet-message-queue = { default-features = false , version = "28.0.0" }
pallet-session = { default-features = false , version = "25.0.0" }
pallet-sudo = { default-features = false, version = "25.0.0" }
pallet-timestamp = { default-features = false , version = "24.0.0" }
pallet-transaction-payment = { default-features = false , version = "25.0.0" }
pallet-transaction-payment-rpc = { version = "27.0.0" }
pallet-transaction-payment-rpc-runtime-api = { default-features = false , version = "25.0.0" }
sc-basic-authorship = { version = "0.31.0" }
sc-chain-spec = { version = "24.0.0" }
sc-cli = { version = "0.33.0" }
sc-client-api = { version = "25.0.0" }
sc-offchain = { version = "26.0.0" }
sc-consensus = { version = "0.30.0" }
sc-executor = { version = "0.29.0" }
sc-network = { version = "0.31.0" }
sc-network-sync = { version = "0.30.0" }
sc-rpc = { version = "26.0.0" }
sc-service = { version = "0.32.0" }
sc-sysinfo = { version = "24.0.0" }
sc-telemetry = { version = "12.0.0" }
sc-tracing = { version = "25.0.0" }
sc-transaction-pool = { version = "25.0.0" }
sc-transaction-pool-api = { version = "25.0.0" }
sp-api = { default-features = false , version = "23.0.0" }
sp-block-builder = { default-features = false , version = "23.0.0" }
sp-blockchain = { version = "25.0.0" }
sp-consensus-aura = { default-features = false, version = "0.29.0" }
sp-core = { default-features = false , version = "25.0.0" }
sp-genesis-builder = { default-features = false , version = "0.4.0" }
sp-inherents = { default-features = false , version = "23.0.0" }
sp-io = { version = "27.0.0" }
sp-keystore = { version = "0.31.0" }
sp-offchain = { default-features = false , version = "23.0.0" }
sp-runtime = { default-features = false , version = "28.0.0" }
sp-session = { default-features = false , version = "24.0.0" }
sp-std = { default-features = false , version = "12.0.0" }
sp-timestamp = { version = "23.0.0" }
sp-transaction-pool = { default-features = false , version = "23.0.0" }
sp-version = { default-features = false , version = "26.0.0" }
substrate-frame-rpc-system = { version = "25.0.0"}
substrate-prometheus-endpoint = { version = "0.16.0" }
substrate-build-script-utils = { version = "9.0.0" }
substrate-wasm-builder = { version = "14.0.0" }

# Polkadot
pallet-xcm = { default-features = false, version = "4.0.0" }
polkadot-cli = { features = ["rococo-native"], version = "4.0.0" }
polkadot-parachain-primitives = { default-features = false, version = "3.0.0" }
polkadot-primitives = { version = "4.0.0" }
polkadot-runtime-common = { default-features = false, version = "4.0.0" }
xcm = { package = "staging-xcm", default-features = false , version = "4.0.0" }
xcm-executor = { package = "staging-xcm-executor", default-features = false , version = "4.0.0" }
xcm-builder = { package = "staging-xcm-builder", default-features = false , version = "4.0.0" }

# Cumulus
cumulus-client-cli = { version = "0.4.0"}
cumulus-client-collator = { version = "0.4.0"}
cumulus-client-consensus-aura = { version = "0.4.0"}
cumulus-client-consensus-common = { version = "0.4.0"}
cumulus-client-consensus-proposer = { version = "0.4.0"}
cumulus-client-service = { version = "0.4.0"}
cumulus-pallet-aura-ext = { default-features = false , version = "0.4.0" }
cumulus-pallet-dmp-queue = { default-features = false , version = "0.4.0" }
cumulus-pallet-parachain-system = { default-features = false, features = ["parameterized-consensus-hook",] , version = "0.4.0" }
cumulus-pallet-session-benchmarking = { default-features = false, version = "6.0.0" }
cumulus-pallet-xcm = { default-features = false , version = "0.4.0" }
cumulus-pallet-xcmp-queue = { default-features = false , version = "0.4.0" }
cumulus-primitives-core = { default-features = false , version = "0.4.0" }
cumulus-primitives-parachain-inherent = { version = "0.4.0"}
cumulus-primitives-utility = { default-features = false , version = "0.4.0" }
cumulus-relay-chain-interface = { version = "0.4.0"}
pallet-collator-selection = { default-features = false , version = "6.0.0" }
parachain-info = { package = "staging-parachain-info", default-features = false , version = "0.4.0" }
parachains-common = { default-features = false , version = "4.0.0" }