[package]
name = "pop-api"
description = "Easily access the power of Polkadot via the Pop Network"
license = "GPL-3.0-only"
version = "0.0.0"
edition = "2021"

[dependencies]
enumflags2 = { version = "0.7.7" }
ink = { version = "5.0.0", default-features = false }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
sp-io = { version = "31.0.0", default-features = false, features = ["disable_panic_handler", "disable_oom", "disable_allocator"] }
sp-runtime = { version = "32.0.0", default-features = false }

pop-primitives = { path = "../primitives", features = ["devnet"], default-features = false }

[lib]
name = "pop_api"
path = "src/lib.rs"
crate-type = ["rlib"]

[features]
default = ["std"]
std = [
    "enumflags2/std",
    "ink/std",
    "pop-primitives/std",
    "scale/std",
    "scale-info/std",
    "sp-io/std",
    "sp-runtime/std",
]
assets = ["pop-primitives/assets"]
balances = []
nfts = ["pop-primitives/nfts"]
cross-chain = ["pop-primitives/cross-chain"]
