[package]
name = "pop-api"
description = "Easily access the power of Polkadot via the Pop Network"
license = "GPL-3.0-only"
version = "0.0.0"
edition = "2021"

[dependencies]
enumflags2 = { version = "0.7.7" }
inkv4 = { package = "ink", version = "4.3.0", default-features = false, optional = true }
inkv5 = { package = "ink", version = "5.0.0", default-features = false, optional = true }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.6", default-features = false, features = ["derive"] }
sp-io = { version = "23.0.0", default-features = false, features = ["disable_panic_handler", "disable_oom", "disable_allocator"] }
sp-runtime = { version = "24.0", default-features = false }

pop-primitives = { path = "../primitives", default-features = false }

[lib]
name = "pop_api"
path = "src/lib.rs"
crate-type = ["rlib"]

[features]
default = ["std"]
std = [
    "enumflags2/std",
    "pop-primitives/std",
    "scale/std",
    "scale-info/std",
    "sp-io/std",
    "sp-runtime/std",
]
inkv4 = ["dep:inkv4"]
inkv5 = ["dep:inkv5"]
